/// A structured monthly financial review generated by the AI coach.
class MonthlyReview {
  final String headline;
  final String summary;
  final List<String> insights;
  final List<String> tips;
  final List<String> budgetAlerts;
  final String tone;

  const MonthlyReview({
    required this.headline,
    required this.summary,
    required this.insights,
    required this.tips,
    required this.budgetAlerts,
    required this.tone,
  });

  factory MonthlyReview.fromJson(Map<String, dynamic> json) => MonthlyReview(
        headline: (json['headline'] ?? '').toString(),
        summary: (json['summary'] ?? '').toString(),
        insights: _listOfStrings(json['insights']),
        tips: _listOfStrings(json['tips']),
        budgetAlerts: _listOfStrings(json['budget_alerts']),
        tone: (json['tone'] ?? 'neutral').toString(),
      );

  static List<String> _listOfStrings(dynamic v) {
    if (v is List) return v.map((e) => e.toString()).toList();
    return [];
  }
}
